apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-deployment
  labels:
    app: my-k8s-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      project: show-me-the-money
  template:
    metadata:
      labels:
        project: show-me-the-money
    spec:
      containers:
        - name: show-me-the-money-web
          image: jaypeng2015/show-me-the-money:latest
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: my-single-pod-service
  labels:
    env: dev
spec:
  selector:
    project: show-me-the-money
  ports:
    - name: app-listener
      protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
